import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Header from './components/Header'
import { light } from '@clerk/themes';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Clerk App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: light,
        variables: { colorPrimary: '#1e293b' },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <main className="container">
            <div className="flex items-start justify-center min-h-screen">
              <div className="mt-20">
                {children}
              </div>
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
